### ISSUE TITLE
Bayesian Course - v1

### ISSUE THREAD

**Issue by storopoli** [storopoli/Bayesian-Statistics#7]
# TODO:

- [X] **What is Bayesian Statistics?**
- [X] **Common Probability Distributions**
- [X] **Priors**
- [X] **Predictive Checks**
- [X] **Bayesian Linear Regression**
- [x] **Bayesian Logistic Regression**
- [x] **Bayesian Ordinal Regression**
   - [x] Ordinal Regression: [12.3 Ordered categorical outcomes](https://shmuma.github.io/rethinking-2ed-julia/12-Chapter%2012.%20Monsters%20and%20Mixtures.html#12.3-Ordered-categorical-outcomes).
- [x] **Bayesian Regression with Count Data: Poisson Regression**
- [x] **Robust Bayesian Regression**
   - [x] Linear Regression with student-t.
   - [x] Robit
   - [x] negative binomial
   - [x] beta binomial
   - [x] Zero-Inflated
- [x] **Hierarchical Models**
   - [x] Varying-Intercept
   - [x] Varying-Slope
   - [x] Varying-Intercept-Slope
   - [x] Correlated Varying-Intercept-Slop: [14.1 Varying slopes by construction](https://shmuma.github.io/rethinking-2ed-julia/14-Chapter%2014.%20Adventures%20in%20Covariance.html)
- [x] **Markov Chain Monte Carlo (MCMC) and Model Metrics**
- [x] **Hierarchical Models: Centered versus Non-Centered Parametrization**
   - [x] Non-Centered versus Centered Parametrization after MCMC lecture, see the explanation in [Stan's User Guide](https://mc-stan.org/docs/2_29/stan-users-guide/reparameterization.html#non-centered-parameterization):
      > Sometimes the group-level effects do not constrain the hierarchical distribution tightly. Examples arise when there are not many groups, or when the inter-group variation is high. In such cases, hierarchical models can be made much more efficient by shifting the data's correlation with the parameters to the hyperparameters.
- [x] **Model Comparison: Cross-Validation and Other Metrics**
- [ ] **ODE Solvers inside a MCMC Sampler**
   - [ ] Simple SIR example?

---

## Models

> OBS: folders `stan/` and `turing/`.

- [x] **Predictive Checks**:
   - [x] Stan
   - [x] Turing
- [x] **Bayesian Linear Regression**:
   - [x] Stan:
      - [x] naive
      - [x] optimized with [`normal_id_glm`](https://mc-stan.org/docs/functions-reference/normal-id-glm.html)
   - [x] Turing 
- [x] **Bayesian Logistic Regression**:
   - [x] Stan:
      - [x] Bernoulli:
         - [x] naive
         - [x] optimized with [`bernoulli_logit_glm`](https://mc-stan.org/docs/functions-reference/bernoulli-logit-glm.html)
      - [x] binomial:
         - [x] naive
         - [x] AFAIK we don't have optimized `_logit_glm` for binomial
   - [x] Turing:
      - [x] Bernoulli
      - [x] binomial
- [x] **Bayesian Ordinal Regression**:
   - [x] Stan:
      - [x] naive
      - [x] optimized with [`ordered_logistic_glm`](https://mc-stan.org/docs/functions-reference/ordered-logistic-generalized-linear-model-ordinal-regression.html)
   - [x] Turing: [12.3 Ordered categorical outcomes](https://shmuma.github.io/rethinking-2ed-julia/12-Chapter%2012.%20Monsters%20and%20Mixtures.html#12.3-Ordered-categorical-outcomes).
- [x] **Bayesian Regression with Count Data: Poisson Regression**:
   - [x] Stan:
      - [x] naive
      - [x] optimized with [`poisson_log_glm`](https://mc-stan.org/docs/functions-reference/poisson-log-glm.html)
   - [x] Turing
- [x] **Robust Bayesian Regression**:
   - [x] beta binomial:
      - [x] Stan
      - [x] Turing: [12.1 Over-dispersed counts ](https://shmuma.github.io/rethinking-2ed-julia/12-Chapter%2012.%20Monsters%20and%20Mixtures.html#12.1-Over-dispersed-counts).
   - [x] negative binomial:
      - [x] Stan `neg_binomial_2`:
         - [x] naive
         - [x] optimized with [`neg_binom_2_log_glm`](https://mc-stan.org/docs/functions-reference/neg-binom-2-log-glm.html)
   - [x] Zero-Inflated:
      - [x] Stan
      - [x] Turing: [12.2 Zero-inflated outcomes](https://shmuma.github.io/rethinking-2ed-julia/12-Chapter%2012.%20Monsters%20and%20Mixtures.html#12.2-Zero-inflated-outcomes).
   - [x] Robit:
      - [x]  Stan
      - [x] Turing: same as Zero-Inflated (custom `Struct` with `logpdf` and `rand`). Test results against Gelman ROS.
- [ ] **Hierarchical Models**:
   - [x] Stan:
      - [x] Varying-Intercept
      - [x] Varying-Slope
      - [x] Varying-Intercept-Slope
      - [x] Correlated Varying-Intercept-Slope
   - [ ] Turing:
      - [x] Varying-Intercept
      - [x] Varying-Slope
      - [x] Varying-Intercept-Slope
      - [ ] Correlated Varying-Intercept-Slope: [14.1 Varying slopes by construction](https://shmuma.github.io/rethinking-2ed-julia/14-Chapter%2014.%20Adventures%20in%20Covariance.html) 
- [x] Non-Centered versus Centered Parametrization:
   - [x] Stan:
      - [x] Varying-Intercept
      - [x] Varying-Slope
      - [x] Varying-Intercept-Slope
      - [x] Correlated Varying-Intercept-Slope
   - [x] Turing:
      - [x] Varying-Intercept
      - [x] Varying-Slope
      - [x] Varying-Intercept-Slope
      - [x] Correlated Varying-Intercept-Slope: [14.1 Varying slopes by construction](https://shmuma.github.io/rethinking-2ed-julia/14-Chapter%2014.%20Adventures%20in%20Covariance.html) 
- [x] **Model Comparison: Cross-Validation and Other Metrics**:
   - [x] Turing
- [ ] **ODE Solvers inside a MCMC Sampler**:
   - [ ] Simple SIR example?
      - [ ] Stan
      - [ ] Turing

### Data:

- [ ] Everything should be simulated data
- [ ] Hierarchical Models should have centered parametrization first, make sure simulations don't screw up Rhat or ESS
- [ ] Non-centered parametrization should show centered parametrization failure (divergences, ESS and Rhat) then show how non-centered parametrization overcome this.
